export const DOCUMENT_TYPES = {
  AADHAR:          'aadhar',
  PAN:             'pan',
  TENTH_CERT:      'tenth_certificate',
  TWELFTH_CERT:    'twelfth_certificate',
  TRANSFER_CERT:   'transfer_certificate',
  CONDUCT_CERT:    'conduct_certificate',
  INCOME_CERT:     'income_certificate',
  CASTE_CERT:      'caste_certificate',
  MIGRATION_CERT:  'migration_certificate',
  PHOTO:           'passport_photo',
  BANK_PASSBOOK:   'bank_passbook',
  MEDICAL_CERT:    'medical_certificate',
};

export const DOCUMENT_LIST = [
  {
    id:          'aadhar',
    type:        DOCUMENT_TYPES.AADHAR,
    title:       'Aadhar Card',
    description: 'Front and back of Aadhar card',
    icon:        '🪪',
    required:    true,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'pan',
    type:        DOCUMENT_TYPES.PAN,
    title:       'PAN Card',
    description: 'Permanent Account Number card',
    icon:        '💳',
    required:    false,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'tenth_certificate',
    type:        DOCUMENT_TYPES.TENTH_CERT,
    title:       '10th Certificate',
    description: 'SSC / 10th class marks memo',
    icon:        '📜',
    required:    true,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   5,
  },
  {
    id:          'twelfth_certificate',
    type:        DOCUMENT_TYPES.TWELFTH_CERT,
    title:       '12th / Intermediate Certificate',
    description: 'HSC / Intermediate marks memo',
    icon:        '📜',
    required:    true,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   5,
  },
  {
    id:          'transfer_certificate',
    type:        DOCUMENT_TYPES.TRANSFER_CERT,
    title:       'Transfer Certificate (TC)',
    description: 'TC from previous institution',
    icon:        '📋',
    required:    true,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'conduct_certificate',
    type:        DOCUMENT_TYPES.CONDUCT_CERT,
    title:       'Conduct Certificate',
    description: 'Good conduct certificate from previous institution',
    icon:        '📄',
    required:    true,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'income_certificate',
    type:        DOCUMENT_TYPES.INCOME_CERT,
    title:       'Income Certificate',
    description: 'Family income certificate issued by MRO / Tahsildar',
    icon:        '💰',
    required:    false,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'caste_certificate',
    type:        DOCUMENT_TYPES.CASTE_CERT,
    title:       'Caste Certificate',
    description: 'Caste certificate issued by competent authority',
    icon:        '📃',
    required:    false,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'migration_certificate',
    type:        DOCUMENT_TYPES.MIGRATION_CERT,
    title:       'Migration Certificate',
    description: 'Required for students from other boards/universities',
    icon:        '📑',
    required:    false,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'passport_photo',
    type:        DOCUMENT_TYPES.PHOTO,
    title:       'Passport Size Photo',
    description: 'Recent passport size photograph',
    icon:        '🖼️',
    required:    true,
    allowedTypes: ['image/jpeg', 'image/png'],
    maxSizeMB:   1,
  },
  {
    id:          'bank_passbook',
    type:        DOCUMENT_TYPES.BANK_PASSBOOK,
    title:       'Bank Passbook',
    description: 'First page of student bank passbook',
    icon:        '🏦',
    required:    false,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
  {
    id:          'medical_certificate',
    type:        DOCUMENT_TYPES.MEDICAL_CERT,
    title:       'Medical / Fitness Certificate',
    description: 'Medical fitness certificate from registered doctor',
    icon:        '🏥',
    required:    false,
    allowedTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    maxSizeMB:   2,
  },
];

export const DOCUMENT_STATUS = {
  NOT_UPLOADED: 'not_uploaded',
  PENDING:      'pending',
  APPROVED:     'approved',
  REJECTED:     'rejected',
};

export const DOCUMENT_STATUS_LABELS = {
  not_uploaded: 'Not Uploaded',
  pending:      'Pending Review',
  approved:     'Approved',
  rejected:     'Rejected',
};

export const REQUIRED_DOCUMENTS = DOCUMENT_LIST.filter((d) => d.required);
export const OPTIONAL_DOCUMENTS = DOCUMENT_LIST.filter((d) => !d.required);

export const getDocumentById   = (id)   => DOCUMENT_LIST.find((d) => d.id === id)   || null;
export const getDocumentByType = (type) => DOCUMENT_LIST.find((d) => d.type === type) || null;